[package]
name = "tidlers"
version = "0.1.0"
edition = "2024"

[dependencies]
# base64 = "0.22.1"
# rand = "0.9.1"
reqwest = { version = "0.12.22", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
# sha2 = "0.10.9"
thiserror = "2.0.12"
tokio = "1.46.1"
url = "2.5.4"
